### ISSUE TITLE
Framework Usage

### ISSUE THREAD

**Issue by ProfliX** [CubBossa/TinyTranslations#10]
Can you please code one plugin, or anything to give more explanation how to exactly use this framework, i know Devotions already exists, but i need some simple & straight forward example to help me out easily integrate this in my plugin.

**Comment by CubBossa** [comment]
Thanks for pointing it out :) adding one

**Comment by ProfliX** [comment]
> Thanks for pointing it out :) adding one

Thank you very much! :) However i still dont get only one thing, how do owners configure original en.yml (which is not found) ?
Can you explain this to me or something please, i really need this framework, im coding custom death messages plugin

**Comment by CubBossa** [comment]
So when you create a message via `new MessageBuilder()`, you can call `withDefault(String)`, which is the dictionary entry for Locale.ENGLISH. Instead of that step, you could create the en.yml by hand. Basically checkout Messages.class and when calling `MessageTranslator#saveLocale(Locale.ENLGISH)` you make sure that all defaults from that class will be added into `en.yml`.

If you do however create your en.yml by hand, you have to make sure to also save the file as resource when loading the plugin
In words: in onEnable check if "yourplugin/lang/en.yml" exists and if not call "saveResource" from bukkit

**Comment by ProfliX** [comment]
> So when you create a message via `new MessageBuilder()`, you can call `withDefault(String)`, which is the dictionary entry for Locale.ENGLISH. Instead of that step, you could create the en.yml by hand. Basically checkout Messages.class and when calling `MessageTranslator#saveLocale(Locale.ENLGISH)` you make sure that all defaults from that class will be added into `en.yml`.
> 
> If you do however create your en.yml by hand, you have to make sure to also save the file as resource when loading the plugin In words: in onEnable check if "yourplugin/lang/en.yml" exists and if not call "saveResource" from bukkit

Can you give me some code example here please.. It would mean a lot to me

**Comment by CubBossa** [comment]
Added some extra lines, have a look and tell me if it helped :D

**Comment by ProfliX** [comment]
> Added some extra lines, have a look and tell me if it helped :D

Thank you very much!!! For a long time now i've been looking for good translations framework and i found it! If you want you can check out my project im doing rn (DeluxeDeath), i will include this framework, it does help out a ton, specially when you want to code custom death messages plugin with per locale support!

**Comment by CubBossa** [comment]
Awesome! Let me know if you encounter any issues.
Yeah you can even mix up with vanilla translations :D just use `<tr:entity.minecraft.skeleton>` or whatever. When using TinyTranslations-bukkit, entity types are rendered as translatables automatically, so if you call `Messages.DEATH_XY.insertObject("killer", entity.getEntityType())` it turns to `<tr:entity.minecraft.skeleton>` for example.
When you're plugin all done I'll add it as reference if you are okay with that?

**Comment by ProfliX** [comment]
> Awesome! Let me know if you encounter any issues. Yeah you can even mix up with vanilla translations :D just use tr:entity.minecraft.skeleton or whatever. When using TinyTranslations-bukkit, entity types are rendered as translatables automatically, so if you call `Messages.DEATH_XY.insertObject("killer", entity.getEntityType())` it turns to tr:entity.minecraft.skeleton for example. When you're plugin all done I'll add it as reference if you are okay with that?

Yeah ofcourse! When im completely done with coding it! :)

**Comment by ProfliX** [comment]
> Awesome! Let me know if you encounter any issues. Yeah you can even mix up with vanilla translations :D just use `<tr:entity.minecraft.skeleton>` or whatever. When using TinyTranslations-bukkit, entity types are rendered as translatables automatically, so if you call `Messages.DEATH_XY.insertObject("killer", entity.getEntityType())` it turns to `<tr:entity.minecraft.skeleton>` for example. When you're plugin all done I'll add it as reference if you are okay with that?

Btw i forgot to ask, which versions this framework supports? Is it okay if i use java 8 and spigot 1.13 (i kinda look to make this plugin to work for all Minecraft versions)

**Comment by CubBossa** [comment]
I sadly am restricted to what adventure supports, which is only java 17 and down to 1.13 i believe? I don't add further limitations than they do but since they are pretty much standard now I wanna stick to their tools. Maybe it works on lower versions tho gotta do some tests

**Comment by ProfliX** [comment]
> I sadly am restricted to what adventure supports, which is only java 17 and down to 1.13 i believe? I don't add further limitations than they do but since they are pretty much standard now I wanna stick to their tools. Maybe it works on lower versions tho gotta do some tests

Nvm i will add only Minecraft 1.16+ support, who uses outdated software anyways

Quick Update: Already made messages for "death causes", now only left to add defaults and placeholders, translations will do AI for now xd

**Comment by ProfliX** [comment]
> > I sadly am restricted to what adventure supports, which is only java 17 and down to 1.13 i believe? I don't add further limitations than they do but since they are pretty much standard now I wanna stick to their tools. Maybe it works on lower versions tho gotta do some tests
> 
> Nvm i will add only Minecraft 1.16+ support, who uses outdated software anyways
> 
> Quick Update: Already made messages for "death causes", now only left to add defaults and placeholders, translations will do AI for now xd

Do you have maybe discord? I would like to add you

**Comment by CubBossa** [comment]
Sure, its leob99 
And server for support: https://discord.com/invite/wDecCCRXFv
